apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: backend-api
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
    cnapp.demo/intentional-risk: "true"
    cnapp.demo/risk-id: vuln-6
  annotations:
    # vuln-6: IRSA bridge — <ACCT> substituted in overlays/eks (M9).
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCT>:role/taskvault-backend-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
    cnapp.demo/intentional-risk: "true"
    cnapp.demo/risk-id: vuln-6
  annotations:
    # vuln-6: IRSA bridge — <ACCT> substituted in overlays/eks (M9).
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCT>:role/taskvault-worker-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-migrator-sa
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: db-migrator
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-job-sa
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: report-job
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
