apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: backend-api
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: backend-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: worker-internal-service
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
---
# T104 (optional): scrape /metrics from backend pods.
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: demo-prod
  labels:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: backend-api
    app.kubernetes.io/part-of: taskvault-demo
    app.kubernetes.io/managed-by: github-actions
    cnapp.demo/environment: demo-prod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: taskvault
    app.kubernetes.io/component: backend-api
  ports:
    - name: metrics
      port: 8080
      targetPort: http
      protocol: TCP
